{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-hpa
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.app.name }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.CPUThreshhold }}
{{- end }}