// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: pb/auth/group_permission.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId      string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	PermissionId string `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
}

func (x *GroupPermission) Reset() {
	*x = GroupPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_auth_group_permission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPermission) ProtoMessage() {}

func (x *GroupPermission) ProtoReflect() protoreflect.Message {
	mi := &file_pb_auth_group_permission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPermission.ProtoReflect.Descriptor instead.
func (*GroupPermission) Descriptor() ([]byte, []int) {
	return file_pb_auth_group_permission_proto_rawDescGZIP(), []int{0}
}

func (x *GroupPermission) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupPermission) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type FindGroupPermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUserId string `protobuf:"bytes,1,opt,name=session_user_id,json=sessionUserId,proto3" json:"session_user_id"`
	GroupId       string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	PermissionId  string `protobuf:"bytes,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
}

func (x *FindGroupPermissionRequest) Reset() {
	*x = FindGroupPermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_auth_group_permission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGroupPermissionRequest) ProtoMessage() {}

func (x *FindGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_auth_group_permission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*FindGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_pb_auth_group_permission_proto_rawDescGZIP(), []int{1}
}

func (x *FindGroupPermissionRequest) GetSessionUserId() string {
	if x != nil {
		return x.SessionUserId
	}
	return ""
}

func (x *FindGroupPermissionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FindGroupPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type CreateGroupPermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUserId string `protobuf:"bytes,1,opt,name=session_user_id,json=sessionUserId,proto3" json:"session_user_id"`
	GroupId       string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	PermissionId  string `protobuf:"bytes,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
}

func (x *CreateGroupPermissionRequest) Reset() {
	*x = CreateGroupPermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_auth_group_permission_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupPermissionRequest) ProtoMessage() {}

func (x *CreateGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_auth_group_permission_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_pb_auth_group_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupPermissionRequest) GetSessionUserId() string {
	if x != nil {
		return x.SessionUserId
	}
	return ""
}

func (x *CreateGroupPermissionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type DeleteGroupPermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUserId string `protobuf:"bytes,1,opt,name=session_user_id,json=sessionUserId,proto3" json:"session_user_id"`
	GroupId       string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	PermissionId  string `protobuf:"bytes,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id"`
}

func (x *DeleteGroupPermissionRequest) Reset() {
	*x = DeleteGroupPermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_auth_group_permission_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupPermissionRequest) ProtoMessage() {}

func (x *DeleteGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_auth_group_permission_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_pb_auth_group_permission_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteGroupPermissionRequest) GetSessionUserId() string {
	if x != nil {
		return x.SessionUserId
	}
	return ""
}

func (x *DeleteGroupPermissionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DeleteGroupPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

var File_pb_auth_group_permission_proto protoreflect.FileDescriptor

var file_pb_auth_group_permission_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x70, 0x62, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x22, 0x51, 0x0a, 0x0f, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a,
	0x1a, 0x46, 0x69, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a,
	0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_auth_group_permission_proto_rawDescOnce sync.Once
	file_pb_auth_group_permission_proto_rawDescData = file_pb_auth_group_permission_proto_rawDesc
)

func file_pb_auth_group_permission_proto_rawDescGZIP() []byte {
	file_pb_auth_group_permission_proto_rawDescOnce.Do(func() {
		file_pb_auth_group_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_auth_group_permission_proto_rawDescData)
	})
	return file_pb_auth_group_permission_proto_rawDescData
}

var file_pb_auth_group_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_auth_group_permission_proto_goTypes = []interface{}{
	(*GroupPermission)(nil),              // 0: pb.auth.GroupPermission
	(*FindGroupPermissionRequest)(nil),   // 1: pb.auth.FindGroupPermissionRequest
	(*CreateGroupPermissionRequest)(nil), // 2: pb.auth.CreateGroupPermissionRequest
	(*DeleteGroupPermissionRequest)(nil), // 3: pb.auth.DeleteGroupPermissionRequest
}
var file_pb_auth_group_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_auth_group_permission_proto_init() }
func file_pb_auth_group_permission_proto_init() {
	if File_pb_auth_group_permission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_auth_group_permission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_auth_group_permission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindGroupPermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_auth_group_permission_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupPermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_auth_group_permission_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupPermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_auth_group_permission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_auth_group_permission_proto_goTypes,
		DependencyIndexes: file_pb_auth_group_permission_proto_depIdxs,
		MessageInfos:      file_pb_auth_group_permission_proto_msgTypes,
	}.Build()
	File_pb_auth_group_permission_proto = out.File
	file_pb_auth_group_permission_proto_rawDesc = nil
	file_pb_auth_group_permission_proto_goTypes = nil
	file_pb_auth_group_permission_proto_depIdxs = nil
}
