app:
  name: auth-service
  group: app
  container:
    image: krobus00/auth-service
    version: v0.1.1
    ports:
      http: 3000
      grpc: 5000
      metrics: 7000
  service:
    type: ClusterIP
    httpPort: 9080
    grpcPort: 9180
    metricsPort: 7000
replicaCount: 1
hpa:
  enable: true
  maxReplicas: 10
  minReplicas: 1
  CPUThreshhold: 80
resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi